sputnik_vm_steps: &sputnik_vm_steps
  steps:
    - restore_cache:
        key: v10-toolchain-{{ arch }}
    - attach_workspace:
        at: ~/
    - run:
        name: Compile SputnikVM-ffi
        command: |
          export GOPATH=$HOME/go
          export PATH=$PATH:$HOME/.cargo/bin
          cd $GOPATH/src/github.com/ethereumclassic/go-ethereum
          make -C vendor/github.com/ETCDEVTeam/sputnikvm-ffi/c
    - persist_to_workspace:
        root: ~/
        paths:
          - go/src/github.com/ethereumclassic/go-ethereum/vendor/github.com/ETCDEVTeam/sputnikvm-ffi/c/libsputnikvm.a

deploy_steps: &deploy_steps
 steps:
   - restore_cache:
       key: v10-toolchain-{{ arch }}
   - attach_workspace:
       at: ~/
   - deploy:
       name: Deploy to Bintray/Artifactory
       command: |
         if [[ $CIRCLE_PROJECT_USERNAME != ethereumclassic ]]; then echo "Deployments only enabled from ethereumclassic/ repo. Exiting." && exit 0; fi
         export GOPATH=$HOME/go
         cd $GOPATH/bin # There is a cached 'geth' executable in here because workflows.
         if [[ ! -f ./geth ]]; then echo "WTF y no haz cached geth??" && exit 1; fi
         # Note that this follow VERSION vars are assuming:
         # - that there IS a last tag
         # - that the tag is named according to semver, with a 'v' prefix, like 'v.5.4.3'
         # TODO: handle cases where these aren't met
         export VERSION=`git describe --tags` # eg. v5.5.2-16-geb15c1474
         export VERSION_SEMVER_FULL=$(git describe --tags $(git rev-list --tags --max-count=1)) eg. v5.5.2
         export VERSION_MAJOR=`echo ${VERSION_SEMVER_FULL} | sed "s/^v\([0-9]*\).*/\1/"` # eg. 5
         export VERSION_MINOR=`echo ${VERSION_SEMVER_FULL} | sed "s/v[0-9]*\.\([0-9]*\).*/\1/"` # eg. the second 5, lulz
         # VERSION_BASE_DIST is essentially an arbitrarily-grouped 'bucket' for sorting releases conveniently with the distributor's "version" idea
         export VERSION_BASE_DIST="v$VERSION_MAJOR.$VERSION_MINOR.x"
         # Ensure versions match, b/c IIRC there was a once-upon-a-time issue with cached builds mismatching.
         ./geth version | awk '/^Version: /{if (ENVIRON["VERSION"] != $2){printf "Expected: \"%s\", got \"%s\"\n",ENVIRON["VERSION"], $2; exit 1}}'
         export ARCHIVE_NAME="ethereum-classic-go-ethereum-$OS_NAME-$VERSION"
         # Archive the executables.
         zip "$GETH_ARCHIVE_NAME.zip" ./geth
         tar -zcf "$GETH_ARCHIVE_NAME.tar.gz" ./geth
         # Create associated hashes of the archives. Use 'tee' so that the hash shows in the CI logs.
         # Since openssl generates output like the below, we use bash's 'read' to echo only the sha.
         # > SHA256(CHANGELOG.md)= e0e8d8af305a3d90dc92e429c379c5c119c23786599f1e185639aafa4fe6163f
         openssl dgst -sha256 "$GETH_ARCHIVE_NAME.zip" | while read -r fn sha; do echo "$sha"; done | tee "$GETH_ARCHIVE_NAME.zip.sha256"
         openssl dgst -sha256 "$GETH_ARCHIVE_NAME.tar.gz" | while read -r fn sha; do echo "$sha"; done | tee "$GETH_ARCHIVE_NAME.tar.gz.sha256"
         # Get jfrog for Bintray OR Artifactory deploys
         curl -fL https://getcli.jfrog.io | sh
         # Configure Bintray OR Artifactory creds.
         ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_APIKEY --interactive=false
         # ./jfrog bt config --url $BINTRAY_URL --user $BINTRAY_USER --apikey $BINTRAY_APIKEY --interactive=false
         # Upload files.
         # Usage: jfrog rt u [command options] <source pattern> <target pattern>
         #   The second argument specifies the location within Bintray for uploaded file, in the form of subject/repository/package/version.
         ./jfrog rt upload "*.zip" "ethereumclassic/go-ethereum/$VERSION_BASE_DIST"
         ./jfrog rt upload "*.tar.gz" "ethereumclassic/go-ethereum/$VERSION_BASE_DIST"
         ./jfrog rt upload "*.sha256" "ethereumclassic/go-ethereum/$VERSION_BASE_DIST"

unit_tests_steps: &unit_tests_steps
  steps:
    - restore_cache:
        key: v10-toolchain-{{ arch }}
    - attach_workspace:
        at: ~/
    - run:
        name: Run unit tests
        command: |
          export GOPATH=$HOME/go
          export GOBIN=$GOPATH/bin
          export PATH=$PATH:$GOBIN
          export TAGS="netgo deterministic"
          if [ $USE_SPUTNIK_VM == true ]; then
            export CGO_LDFLAGS="$GOPATH/src/github.com/ethereumclassic/go-ethereum/vendor/github.com/ETCDEVTeam/sputnikvm-ffi/c/libsputnikvm.a -ldl"
            if [ "$(uname)" == "Darwin" ]; then
              export CGO_LDFLAGS="$CGO_LDFLAGS -lresolv"
            fi
            export TAGS="sputnikvm $TAGS"
          fi
          export PATH=$PATH:$HOME/.cargo/bin
          cd $GOPATH/src/github.com/ethereumclassic/go-ethereum
          go env
          # Since core/ and tests/ packages are run deterministically, we can safely
          # infer that SputnikVM is functioning the same as the native VM without running
          # the schroedinger nondeterministic tests with sputnik enabled.
          go test -ldflags "-X github.com/ethereumclassic/go-ethereum/core.UseSputnikVM=$USE_SPUTNIK_VM" -tags="$TAGS" ./...
          schroedinger -t 5 -f ./schroedinger-tests.txt

bats_tests_steps: &bats_tests_steps
    steps:
      - restore_cache:
          key: v10-toolchain-{{ arch }}
      - attach_workspace:
          at: ~/
      - run:
          name: Run bats tests
          command: |
            export GOPATH=$HOME/go
            export CGO_LDFLAGS="$GOPATH/src/github.com/ethereumclassic/go-ethereum/vendor/github.com/ETCDEVTeam/sputnikvm-ffi/c/libsputnikvm.a -ldl"
            if [ "$(uname)" == "Darwin" ]; then
              export CGO_LDFLAGS="$CGO_LDFLAGS -lresolv"
            else
              export EXT_LD_FLAGS="-extldflags=-static"
            fi
            export PATH=$PATH:$HOME/.cargo/bin:$HOME/bin
            cd $GOPATH/src/github.com/ethereumclassic/go-ethereum
            # go install ... doesn't work with netgo on CircleCI on Linux
            go build -tags="sputnikvm netgo" -ldflags "$EXT_LD_FLAGS -X main.Version=`git describe --tags`" ./cmd/geth
            mkdir -p $GOPATH/bin
            mv ./geth $GOPATH/bin/
            bats tests/bats
      - persist_to_workspace:
          root: ~/
          paths:
              - go/*

version: 2
jobs:
  mac_env_setup:
    macos:
      xcode: "9.0"
    steps:
      - restore_cache:
          key: v10-toolchain-{{ arch }}
      - run:
          name: Prepare directories
          command: |
            export GOPATH=$HOME/go
            export PATH=$PATH:$HOME/.cargo/bin
            mkdir -p $GOPATH/src/github.com/ethereumclassic
      - checkout:
          path:  ~/go/src/github.com/ethereumclassic/go-ethereum
      - run:
          name: Install required software
          command: |
            export GOPATH=$HOME/go
            export PATH=$PATH:$HOME/.cargo/bin]
            curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
            if [ ! -x /usr/local/bin/go ]; then
              brew update
              export BDIR="$(brew --repo homebrew/core)" && echo "$BDIR" && git -C "$BDIR" reset --hard master && git -C "$BDIR" fetch origin ac2308d7640e45de0de1dbcbb6d4f42fcdd8adde && git -C "$BDIR" checkout FETCH_HEAD && HOMEBREW_NO_AUTO_UPDATE=1 brew install go && brew switch go 1.9.3 && git -C "$BDIR" checkout master && unset BDIR
              brew info go
              go version
              brew install bats
              brew install gpg2
              go get github.com/etcdevteam/go-schroedinger/cmd/schroedinger/...
            fi
      - persist_to_workspace:
          root: ~/
          paths:
            - go/src/github.com/ethereumclassic/*
      - save_cache:
          key: v10-toolchain-{{ arch }}
          paths:
            - /usr/local/bin/bats
            - /usr/local/bin/go
            - /usr/local/bin/godoc
            - /usr/local/bin/gofmt
            - /usr/local/bin/gpg
            - /usr/local/opt
            - /usr/local/Cellar
            - /usr/local/Homebrew
            - ~/.cargo
            - ~/.rustup
            - ~/go/bin

  linux_env_setup:
    docker:
      - image: circleci/golang:1.9
    steps:
      - restore_cache:
          key: v10-toolchain-{{ arch }}
      - run:
          name: Prepare directories
          command: |
            export GOPATH=$HOME/go
            export PATH=$PATH:$HOME/.cargo/bin
            mkdir -p $GOPATH/src/github.com/ethereumclassic
      - checkout:
          path:  ~/go/src/github.com/ethereumclassic/go-ethereum
      - run:
          name: Install required software
          command: |
            export GOPATH=$HOME/go
            export PATH=$PATH:$HOME/.cargo/bin
            git clone https://github.com/sstephenson/bats.git
            cd bats
            sudo ./install.sh ~/
            curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
            go get github.com/etcdevteam/go-schroedinger/cmd/schroedinger/...
      - persist_to_workspace:
          root: ~/
          paths:
            - go/src/github.com/ethereumclassic/*
      - save_cache:
          key: v10-toolchain-{{ arch }}
          paths:
            - ~/bin
            - ~/libexec
            - ~/.cargo
            - ~/.rustup
            - ~/go/bin

  mac_sputnik_vm:
    macos:
      xcode: "9.0"
    <<: *sputnik_vm_steps

  linux_sputnik_vm:
    docker:
      - image: circleci/golang:1.9
    <<: *sputnik_vm_steps

  mac_evm_unit_tests:
    macos:
      xcode: "9.0"
    environment:
        USE_SPUTNIK_VM: false
    <<: *unit_tests_steps

  linux_evm_unit_tests:
    docker:
      - image: circleci/golang:1.9
    environment:
        GOMAXPROCS: 2
        USE_SPUTNIK_VM: false
    <<: *unit_tests_steps

  mac_sputnikvm_unit_tests:
    macos:
      xcode: "9.0"
    environment:
        USE_SPUTNIK_VM: true
    <<: *unit_tests_steps

  linux_sputnikvm_unit_tests:
    docker:
      - image: circleci/golang:1.9
    environment:
        GOMAXPROCS: 2
        USE_SPUTNIK_VM: true
    <<: *unit_tests_steps

  mac_bats_tests:
    macos:
      xcode: "9.0"
    <<: *bats_tests_steps

  linux_bats_tests:
    docker:
      - image: circleci/golang:1.9
    <<: *bats_tests_steps

#  mac_deploy:
#    macos:
#      xcode: "9.0"
#    <<: *deploy_steps

#  linux_deploy:
#    docker:
#      - image: circleci/golang:1.9
#    <<: *deploy_steps

workflows:
  version: 2
  mac_build:
    jobs:
      - mac_env_setup:
          filters:
            tags:
              only: /.*/
      - mac_sputnik_vm:
          requires:
            - mac_env_setup
          filters:
            tags:
              only: /.*/
      - mac_evm_unit_tests:
          requires:
            - mac_env_setup
          filters:
            tags:
              only: /.*/
      - mac_sputnikvm_unit_tests:
          requires:
            - mac_sputnik_vm
          filters:
            tags:
              only: /.*/
      - mac_bats_tests:
          requires:
            - mac_sputnik_vm
          filters:
            tags:
              only: /.*/
#      - mac_deploy:
#          requires:
#            - mac_evm_unit_tests
#            - mac_sputnikvm_unit_tests
#            - mac_bats_tests
#          filters:
#            branches:
#              only: master
#            tags:
#              only: /.*/

  linux_build:
    jobs:
      - linux_env_setup:
          filters:
            tags:
              only: /.*/
      - linux_sputnik_vm:
          requires:
            - linux_env_setup
          filters:
            tags:
              only: /.*/
      - linux_evm_unit_tests:
          requires:
            - linux_env_setup
          filters:
            tags:
              only: /.*/
      - linux_sputnikvm_unit_tests:
          requires:
            - linux_sputnik_vm
          filters:
            tags:
              only: /.*/
      - linux_bats_tests:
          requires:
            - linux_sputnik_vm
          filters:
            tags:
              only: /.*/
#      - linux_deploy:
#          requires:
#            - linux_evm_unit_tests
#            - linux_sputnikvm_unit_tests
#            - linux_bats_tests
#          filters:
#            branches:
#              only: master
#            tags:
#              only: /.*/
